### ISSUE TITLE
update radarr logo

### ISSUE THREAD

**Issue by thezoggy** [Radarr/radarr.github.io#2]
sonarr updated its logo for v3 awhile ago.. radarr may want to do the same to be in sync
https://github.com/Sonarr/Sonarr/tree/phantom/Logo

makes logo a bit more clean when viewing at smaller sizes

**Comment by thezoggy** [comment]
or update logo to your own so it doesnt look so similar

**Comment by Taloth** [comment]
The second option. Creating Radarr's own identity is definitely preferred.

**Comment by ghost** [comment]
I can probably do something about this in the next few weeks.
