### ISSUE TITLE
Redirect http to https

### ISSUE THREAD

**Issue by frebib** [Radarr/radarr.github.io#3]
Github now supports HTTPS certificates on github.io with custom domains. Have you considered enabling it?

https://blog.github.com/2018-05-01-github-pages-custom-domains-https/

**Comment by galli-leo** [comment]
radarr.video is not hosted on github pages and already uses https

**Comment by frebib** [comment]
My apologies. It appears that HTTP doesn't redirect to HTTP(s). Oversight on my part
