### ISSUE TITLE
radarr

### ISSUE THREAD

**Issue by jdradarr** [Radarr/radarr.github.io#37]
how to open Radarr, it now asks for a sign-on. never had one before??
JIM

**Comment by bakerboy448** [comment]
Please use [Discord](https://radarr.video/discord) for support/questions.

for this issue - see the FAQ / read the auth required helptext better. It's not asking for existing credentials

**Comment by jdradarr** [comment]
ok, FAQ's. On the home page.
thanks for the response.
Jim

**Comment by jdradarr** [comment]
So, where are the FAQ's located????\
