### ISSUE TITLE
Update images for v3

### ISSUE THREAD

**Issue by bakerboy448** [Radarr/radarr.github.io#9]

**Comment by bakerboy448** [comment]
@TRaSH- to provide images for @Qstick

**Comment by TRaSH-** [comment]
I could provide them,
but it would be easier for me if i knew which one are needed.
just going to https://radarr.video/ with the scrolling screenshots isn't easy for me to figure out which one are needed.

**Comment by bakerboy448** [comment]
- [ ] Frequent Updates
- [ ] Movie Files
- [ ] Notifications/Connect
- [ ] Quality Profiles
- [ ] All 3 movie index views
- [ ] Calendar
- [ ] Manual search
- [ ] Automatic Failed Download Handling 
- [ ] (Maybe) Censor all results to generic Movie.(Year) (Chrome Dev Tools)

@TRaSH-

**Comment by TRaSH-** [comment]
Can someone provide me the old images,
So it's easier for me to create the new ones.
This way I also can use the same name as the old one

**Comment by Qstick** [comment]
https://www.github.com/Radarr/radarr.github.io/tree/master/img%2Fslider

https://www.github.com/Radarr/radarr.github.io/tree/master/img%2Ffeatures

**Comment by TRaSH-** [comment]
#10 
Updated v0.2 images to v3
Let me know if you need other images

**Comment by Qstick** [comment]
The old logo backdrop would be the only other bit, if you didn't already hit that

**Comment by TRaSH-** [comment]
you mean this one ?
https://github.com/Radarr/radarr.github.io/blob/master/img/background/logo.png
if so i wouldn't know where to get a new one from


I also was thinking if possible add other screenshots perhaps with a few new features
- Custom Formats
- Collection Lists

**Comment by Qstick** [comment]
> you mean this one ?
> https://github.com/Radarr/radarr.github.io/blob/master/img/background/logo.png
> if so i wouldn't know where to get a new one from
> 
> 
> I also was thinking if possible add other screenshots perhaps with a few new features
> - Custom Formats
> - Collection Lists

Sounds good, I'll handle the logo and hook up the others if you want to add the screens in the repo

**Comment by TRaSH-** [comment]
I'll add them tonight when I get home,
I left all images as png for highest quality.
I kept the same naming.

**Comment by TRaSH-** [comment]
@Qstick  added

**Comment by bakerboy448** [comment]
https://github.com/Radarr/radarr.github.io/commit/5968181c74863be85d690ac835fb4b4258a8cb1e
https://github.com/Radarr/radarr.github.io/commit/6e3930699671a8b944961daa22e3b00e956d3108
